version: '3.8'

services:
  datamap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datamap-backend
    ports:
      - "4142:4142"
    environment:
      - TZ=Africa/Nairobi
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 4142
    networks:
      - datamap-network
#    depends_on:
#      cassandra:
#        condition: service_healthy
    restart: always


#  cassandra:
#    image: cassandra:latest
#    container_name: datamap-cassandra
#    ports:
#      - "9042:9042"
#    env_file:
#      - .env-cassandra
#    volumes:
#      - cassandra-data:/var/lib/cassandra
#    networks:
#      - datamap-network
#    healthcheck:
#      test: [ "CMD-SHELL", "nodetool status | grep -q 'UN'" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5
#    restart: always

  postgres:
    container_name: datamap-postgres
    image: postgres:latest
    env_file:
      - .env-postgres
    environment:
      POSTGRES_USER: datamap
      POSTGRES_DB: datamap
    ports:
      - "5111:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - datamap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U datamap"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped


volumes:
  postgres-data:

networks:
  datamap-network:
    name: datamap-network
    driver: bridge